name: Welcome
version: '${project.version}'
main: cn.paper_card.welcome.Welcome
api-version: 1.20
author: Paper99
folia-supported: true


commands:
  zanzhu:
    permission: welcome.command.zanzhu

  check-progress:
    permission: welcome.command.check-progress

permissions:
  welcome.command.zanzhu:
    default: true

  welcome.command.check-progress:
    default: true
